"""nullable plate_number, add card_uid, add midtrans payment fields

Revision ID: 64a61fdf3593
Revises: 0004
Create Date: 2026-08-24 13:00:05.021343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a61fdf3593'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_events', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('vehicle_histories', sa.Column('status_bayar', sa.String(length=20), server_default='belum_bayar', nullable=False))
    op.add_column('vehicle_histories', sa.Column('midtrans_order_id', sa.String(length=100), nullable=True))
    op.add_column('vehicle_histories', sa.Column('midtrans_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('vehicle_histories', sa.Column('jumlah_bayar', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('vehicle_histories', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_vehicle_histories_midtrans_order_id'), 'vehicle_histories', ['midtrans_order_id'], unique=False)
    op.add_column('vehicle_owners', sa.Column('card_uid', sa.String(length=100), nullable=False))
    op.alter_column('vehicle_owners', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('vehicle_owners', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_vehicle_owners_card_uid'), 'vehicle_owners', ['card_uid'], unique=True)
    op.alter_column('vehicles', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_vehicle_owners_card_uid'), table_name='vehicle_owners')
    op.alter_column('vehicle_owners', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('vehicle_owners', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('vehicle_owners', 'card_uid')
    op.drop_index(op.f('ix_vehicle_histories_midtrans_order_id'), table_name='vehicle_histories')
    op.alter_column('vehicle_histories', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('vehicle_histories', 'jumlah_bayar')
    op.drop_column('vehicle_histories', 'midtrans_transaction_id')
    op.drop_column('vehicle_histories', 'midtrans_order_id')
    op.drop_column('vehicle_histories', 'status_bayar')
    op.alter_column('vehicle_events', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
